export const LOGIN_SUCESS = 'LOGIN_SUCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOADING = 'LOGIN_LOADING';

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';
export const GET_PRODUCTS_LOADING = 'GET_PRODUCTS_LOADING';

export const GET_INFO_SUCCESS = 'GET_INFO_SUCCESS';
export const GET_INFO_FAIL = 'GET_INFO_FAIL';
export const GET_INFO_LOADING = 'GET_INFO_LOADING';

export const GET_SHOP_SUCCESS = 'GET_SHOP_SUCCESS';
export const GET_SHOP_FAIL = 'GET_SHOP_FAIL';
export const GET_SHOP_LOADING = 'GET_SHOP_LOADING';

export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';
export const GET_CATEGORY_LOADING = 'GET_CATEGORY_LOADING';

export const GET_PRODUCT_BY_CATEGORY_SUCCESS =
  'GET_PRODUCT_BY_CATEGORY_SUCCESS';
export const GET_PRODUCT_BY_CATEGORY_FAIL = 'GET_PRODUCT_BY_CATEGORY_FAIL';
export const GET_PRODUCT_BY_CATEGORY_LOADING =
  'GET_PRODUCT_BY_CATEGORY_LOADING';

export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAIL = 'GET_CART_FAIL';
export const GET_CART_LOADING = 'GET_CART_LOADING';

export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const ADD_CART_FAIL = 'ADD_CART_FAIL';
export const ADD_CART_LOADING = 'ADD_CART_LOADING';
